# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7994a7ec17326c405b0e1028c629672ab838b813044020d611f03c57f595e3024b934bafff63fe09737c4f308ef76f64a68e967563379d28409df4425aabcbca

test:
  secret_key_base: 97c4d285613e3b731da9d37389d7bb61014aa0fe78730bc2deb9367467ebdb6db0a82da0400b4cfeaef050268d30362f0bd6d31f02e5bfe9bc8fe33ea3e9b0c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
